# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\anaconda3\Lib\site-packages\PyQt5\uic\Fish_UI\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!
import sys
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1270, 758)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.xiongqi = QtWidgets.QLineEdit(self.centralWidget)
        self.xiongqi.setGeometry(QtCore.QRect(720, 90, 111, 31))
        self.xiongqi.setObjectName("xiongqi")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(620, 90, 71, 31))
        self.label.setScaledContents(False)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(730, 40, 71, 31))
        self.label_2.setScaledContents(False)
        self.label_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_2.setObjectName("label_2")
        self.camera = QtWidgets.QTextEdit(self.centralWidget)
        self.camera.setGeometry(QtCore.QRect(30, 260, 571, 431))
        self.camera.setObjectName("camera")
        self.ip_connect = QtWidgets.QPushButton(self.centralWidget)
        self.ip_connect.setGeometry(QtCore.QRect(420, 50, 113, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ip_connect.setFont(font)
        self.ip_connect.setObjectName("ip_connect")
        self.clear = QtWidgets.QPushButton(self.centralWidget)
        self.clear.setGeometry(QtCore.QRect(1100, 90, 113, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.clear.setFont(font)
        self.clear.setObjectName("clear")
        self.send = QtWidgets.QPushButton(self.centralWidget)
        self.send.setGeometry(QtCore.QRect(940, 90, 113, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.send.setFont(font)
        self.send.setObjectName("send")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(80, 20, 151, 31))
        self.label_3.setScaledContents(False)
        self.label_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_3.setObjectName("label_3")
        self.ip1 = QtWidgets.QLineEdit(self.centralWidget)
        self.ip1.setGeometry(QtCore.QRect(80, 60, 31, 31))
        self.ip1.setObjectName("ip1")
        self.ip2 = QtWidgets.QLineEdit(self.centralWidget)
        self.ip2.setGeometry(QtCore.QRect(120, 60, 31, 31))
        self.ip2.setObjectName("ip2")
        self.ip3 = QtWidgets.QLineEdit(self.centralWidget)
        self.ip3.setGeometry(QtCore.QRect(160, 60, 31, 31))
        self.ip3.setObjectName("ip3")
        self.ip4 = QtWidgets.QLineEdit(self.centralWidget)
        self.ip4.setGeometry(QtCore.QRect(200, 60, 31, 31))
        self.ip4.setObjectName("ip4")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(260, 20, 151, 31))
        self.label_4.setScaledContents(False)
        self.label_4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_4.setObjectName("label_4")
        self.duankouhao = QtWidgets.QLineEdit(self.centralWidget)
        self.duankouhao.setGeometry(QtCore.QRect(290, 60, 91, 31))
        self.duankouhao.setObjectName("duankouhao")
        self.tuoluoyi = QtWidgets.QTextEdit(self.centralWidget)
        self.tuoluoyi.setGeometry(QtCore.QRect(750, 580, 501, 111))
        self.tuoluoyi.setObjectName("tuoluoyi")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(600, 570, 151, 61))
        self.label_5.setScaledContents(False)
        self.label_5.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_5.setObjectName("label_5")
        self.read_tuoluoyi = QtWidgets.QPushButton(self.centralWidget)
        self.read_tuoluoyi.setGeometry(QtCore.QRect(620, 620, 113, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.read_tuoluoyi.setFont(font)
        self.read_tuoluoyi.setObjectName("read_tuoluoyi")
        self.zhuangtai = QtWidgets.QTextEdit(self.centralWidget)
        self.zhuangtai.setGeometry(QtCore.QRect(80, 100, 451, 81))
        self.zhuangtai.setObjectName("zhuangtai")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(210, 200, 151, 61))
        self.label_6.setScaledContents(False)
        self.label_6.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.label_6.setObjectName("label_6")
        self.read_camera = QtWidgets.QPushButton(self.centralWidget)
        self.read_camera.setGeometry(QtCore.QRect(370, 210, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.read_camera.setFont(font)
        self.read_camera.setObjectName("read_camera")
        self.save_tuoluoyi = QtWidgets.QPushButton(self.centralWidget)
        self.save_tuoluoyi.setGeometry(QtCore.QRect(620, 660, 113, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.save_tuoluoyi.setFont(font)
        self.save_tuoluoyi.setObjectName("save_tuoluoyi")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1270, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">胸鳍</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">转动角度</span></p></body></html>"))
        self.ip_connect.setText(_translate("MainWindow", "连接"))
        self.clear.setText(_translate("MainWindow", "清空"))
        self.send.setText(_translate("MainWindow", "发送"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">请输入ip地址</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">请输入端口号</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">陀螺仪数据</span></p></body></html>"))
        self.read_tuoluoyi.setText(_translate("MainWindow", "读取"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">实时视频</span></p></body></html>"))
        self.read_camera.setText(_translate("MainWindow", "读取实时摄像头"))
        self.save_tuoluoyi.setText(_translate("MainWindow", "保存"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

